### ISSUE TITLE
Allow to select fields to display and change

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#13]
On the upload page (and batch edit view) it would be valuable to have a way to select fields to display. To could make batch entry/editing easier by focusing only on a subset of the fields.

**Comment by hacole01** [comment]
this seems functional (tested on edit view), and certainly useful for management of screen/display space. 

Would be a dream for users to be able to have default views of these fields so they don't have to manually select each time (or for them to create multiple views (like you can in Knowledge Workspace) and select as relevant.

**Comment by michellelocke** [comment]
The issue I see with this is that the Built In Attributes are always displayed first and always in the same order, this cannot be changed. It seems to be only the Managed Attributes that I can change the order of. I would like to be able to display any field in any order I want. A lot of those Built In Attributes are not things I will want to edit, but I still might want to see them, but I would rather see Managed Attributes like Catalog Number before the Rights Statement and License. 

I also think it is a requirement (rather than a dream) that we have customizable default views of the fields. It is quite frustrating to have to add Catalog Number and Specimen View each time I upload new images. I would like to be able to be able to make my own template of fields visible and the order they are listed in. I would also like to be able to create multiple templates, say one for images, one for documents, etc.

**Comment by michellelocke** [comment]
Another issue I have with how this function currently works is that it is way too easy to clear all of the attributes from view at once. A number of times I have hit the 'x' and cleared all attributes rather than hitting the arrow for the dropdown menu. Then I have to go back and add everything again. It can't be that easy to clear the view. I think this is why having templates that people can create and modify would be a much better solution. This way they can easily change the view but they have to do it in a very specific and mindful way, rather than constantly having to add and delete fields as they need them.

**Comment by michellelocke** [comment]
One bug I have found with this is that if you clear all of the Built In Attributes at once (hit the 'x' beside the dropdown arrow) it clears all of the Managed Attributes as well and you are left with nothing on the screen. As the 'x' is in the Built In Attributes box, intuitively it means that it should only clear the Built In Attributes, just as only the Managed Attributes are cleared when you hit the 'x' in that box.

Then when you are adding the Attributes back in, if you add any Managed Attribute (ex: Specimen View) then add a Built In Attribute (ex: Digitized By), the Managed Attributes (Specimen View) are then cleared and disappear, meaning you have to add them again. This should not happen.

**Comment by cgendreau** [comment]
Thanks @michellelocke , we will have a look at the issues.

**Comment by cgendreau** [comment]
The reported issues should be solved now. It is also possible to save the template now.

**Comment by michellelocke** [comment]
I still cannot change the order of the Built In Attributes. They always appear first and always in the order they are listed in the Built In Attribute dropdown menu. I want to be able to have the attributes (both Built In and Managed) appear in any order I choose. If I start with a clear slate then the first attribute I add (either Built In or Managed) should always remain first. The next one I add should always remain second. I should be able to have the CatalogNumber appear first then the SpecimenView second, then the Original Filename third, etc.

**Comment by michellelocke** [comment]
The bug reported in my third comment from Dec 18 (regarding clearing of attributes) appears to be resolved. Thank you.

**Comment by michellelocke** [comment]
The templates work great! This is really helpful! I have two additional remarks regarding the templates:

1) It would be helpful to be able to set a default template or have the last template you used remain active each time you edit, until you change it. Currently the user has to select the template they want to use each time they want to edit the attributes.

2) It would be helpful to have templates that are collection wide, and not just specific to each user. This way, when we have 13 students uploading photos, we can select our photo template and not have to recreate it 13 times. The CNC DB allows users to create their own template. Then any other user can copy the template to use for themselves. Alternatively the Collections Managers could set up templates for users to use.

**Comment by michellelocke** [comment]
The template is not available for editing a single record. I would like to use the template to have only the same fields visible to edit in a single record please.
